services:
  - type: web
    name: huggingface-service
    runtime: python
    env: python
    buildCommand: |
      pip install -r requirements.txt
      pip install huggingface_hub
      huggingface-cli login --token $HUGGINGFACE_TOKEN
    startCommand: |
      python main.py
    envVars:
      - key: HUGGINGFACE_TOKEN
        sync: false
