services:
  # A Docker web service
  - type: web
    name: fastapi-example
    runtime: python
    plan: free
    autoDeploy: false
    buildCommand: pip install -r requirements.txt
    startCommand: python main.pyservices:
  - type: web
    name: huggingface-service
    runtime: python
    env: python
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
      huggingface-cli login --token $HUGGINGFACE_TOKEN && python main.py